import { Directive, Output, EventEmitter } from '@angular/core';

import { BaseMapDirective } from './base-map-directive';
import { Ng2MapComponent } from '../components/ng2-map.component';

const INPUTS = [
  'options',
  'circleOptions', 'drawingControl', 'drawingControlOptions', 'drawingMode',
  'map', 'markerOptions', 'polygonOptions', 'polylineOptions', 'rectangleOptions'
];
const OUTPUTS = [
  'circlecomplete', 'markercomplete', 'overlaycomplete',
  'polygoncomplete', 'polylinecomplete', 'rectanglecomplete'
];

@Directive({
  selector: 'ng2-map > drawing-manager',
  inputs: INPUTS,
  outputs: OUTPUTS,
})
export class DrawingManager extends BaseMapDirective {
  @Output() public circlecomplete: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public markercomplete: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public overlaycomplete: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public polygoncomplete: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public polylinecomplete: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public rectanglecomplete: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js

  public options: any; // generated by ngc-pre-compiler.js
  public circleOptions: any; // generated by ngc-pre-compiler.js
  public drawingControl: any; // generated by ngc-pre-compiler.js
  public drawingControlOptions: any; // generated by ngc-pre-compiler.js
  public drawingMode: any; // generated by ngc-pre-compiler.js
  public map: any; // generated by ngc-pre-compiler.js
  public markerOptions: any; // generated by ngc-pre-compiler.js
  public polygonOptions: any; // generated by ngc-pre-compiler.js
  public polylineOptions: any; // generated by ngc-pre-compiler.js
  public rectangleOptions: any; // generated by ngc-pre-compiler.js

  @Output() public initialized$: EventEmitter<any> = new EventEmitter();

  constructor(ng2MapComp: Ng2MapComponent) {
    super(ng2MapComp, 'DrawingManager', INPUTS, OUTPUTS);
    this.libraryName = 'drawing';
  }
}
