import {Directive, Output, EventEmitter, Input} from '@angular/core';

import { BaseMapDirective } from './base-map-directive';
import { Ng2MapComponent } from '../components/ng2-map.component';

const INPUTS = [ 'data', 'dissipating', 'gradient', 'maxIntensity', 'opacity', 'radius', 'options' ];

@Directive({
  selector: 'ng2-map > heatmap-layer',
})
export class HeatmapLayer extends BaseMapDirective {
  @Input() public data: any; // generated by ngc-pre-compiler.js
  @Input() public dissipating: any; // generated by ngc-pre-compiler.js
  @Input() public gradient: any; // generated by ngc-pre-compiler.js
  @Input() public maxIntensity: any; // generated by ngc-pre-compiler.js
  @Input() public opacity: any; // generated by ngc-pre-compiler.js
  @Input() public radius: any; // generated by ngc-pre-compiler.js
  @Input() public options: any; // generated by ngc-pre-compiler.js

  @Output() public initialized$: EventEmitter<any> = new EventEmitter();

  public libraryName: string;

  constructor(ng2MapComp: Ng2MapComponent) {
    super(ng2MapComp, 'HeatmapLayer', INPUTS);
    this.libraryName = 'visualization';
  }
}
