import {Directive, Output, EventEmitter, Input} from '@angular/core';

import { BaseMapDirective } from './base-map-directive';
import { Ng2MapComponent } from '../components/ng2-map.component';

const INPUTS = [ 'clickable', 'preserveViewport', 'screenOverlays', 'suppressInfoWindows', 'url', 'zIndex', 'options' ];
const OUTPUTS = [ 'click', 'defaultviewport_changed', 'status_changed' ];

@Directive({
  selector: 'ng2-map > kml-layer',
})
export class KmlLayer extends BaseMapDirective {
  @Output() public click: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public defaultviewport_changed: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public status_changed: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public initialized$: EventEmitter<any> = new EventEmitter();

  @Input() public clickable: any; // generated by ngc-pre-compiler.js
  @Input() public preserveViewport: any; // generated by ngc-pre-compiler.js
  @Input() public screenOverlays: any; // generated by ngc-pre-compiler.js
  @Input() public suppressInfoWindows: any; // generated by ngc-pre-compiler.js
  @Input() public url: any; // generated by ngc-pre-compiler.js
  @Input() public zIndex: any; // generated by ngc-pre-compiler.js
  @Input() public options: any; // generated by ngc-pre-compiler.js

  constructor(ng2MapComp: Ng2MapComponent) {
    super(ng2MapComp, 'KmlLayer', INPUTS, OUTPUTS);
  }
}
