import {Directive, Output, EventEmitter, OnInit, Input} from '@angular/core';

import { BaseMapDirective } from './base-map-directive';
import { Ng2MapComponent } from '../components/ng2-map.component';

// ng2-map specific inputs: geoFallbackPosition
const INPUTS = [
  'anchorPoint', 'animation', 'clickable', 'cursor', 'draggable', 'icon', 'label', 'opacity',
  'optimized', 'place', 'position', 'shape', 'title', 'visible', 'zIndex', 'options',
  'geoFallbackPosition'
];
const OUTPUTS = [
  'animationChanged', 'click', 'clickableChanged', 'cursorChanged', 'dblclick', 'drag', 'dragend', 'draggableChanged',
  'dragstart', 'flatChanged', 'iconChanged', 'mousedown', 'mouseout', 'mouseover', 'mouseup', 'positionChanged', 'rightclick',
  'shapeChanged', 'titleChanged', 'visibleChanged', 'zindexChanged'
];

@Directive({
  selector: 'ng2-map > marker',
})
export class Marker extends BaseMapDirective implements OnInit {
  @Output() public animationChanged: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public click: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public clickableChanged: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public cursorChanged: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dblclick: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public drag: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dragend: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public draggableChanged: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dragstart: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public flatChanged: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public iconChanged: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mousedown: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mouseout: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mouseover: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mouseup: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public positionChanged: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public rightclick: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public shapeChanged: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public titleChanged: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public visibleChanged: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public zindexChanged: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public initialized$: EventEmitter<any> = new EventEmitter();

  @Input() public anchorPoint: any; // generated by ngc-pre-compiler.js
  @Input() public animation: any; // generated by ngc-pre-compiler.js
  @Input() public clickable: any; // generated by ngc-pre-compiler.js
  @Input() public cursor: any; // generated by ngc-pre-compiler.js
  @Input() public draggable: any; // generated by ngc-pre-compiler.js
  @Input() public icon: any; // generated by ngc-pre-compiler.js
  @Input() public label: any; // generated by ngc-pre-compiler.js
  @Input() public opacity: any; // generated by ngc-pre-compiler.js
  @Input() public optimized: any; // generated by ngc-pre-compiler.js
  @Input() public place: any; // generated by ngc-pre-compiler.js
  @Input() public position: any; // generated by ngc-pre-compiler.js
  @Input() public shape: any; // generated by ngc-pre-compiler.js
  @Input() public title: any; // generated by ngc-pre-compiler.js
  @Input() public visible: any; // generated by ngc-pre-compiler.js
  @Input() public zIndex: any; // generated by ngc-pre-compiler.js
  @Input() public options: any; // generated by ngc-pre-compiler.js
  @Input() public geoFallbackPosition: any; // generated by ngc-pre-compiler.js

  public mapObject: google.maps.Marker;
  public objectOptions: google.maps.MarkerOptions = <google.maps.MarkerOptions>{};

  constructor(private ng2MapComp: Ng2MapComponent) {
    super(ng2MapComp, 'Marker', INPUTS, OUTPUTS);
    console.log('marker constructor', 9999999 );
  }

  // Initialize this map object when map is ready
  ngOnInit() {
    if (this.ng2MapComponent.mapIdledOnce) { // map is ready already
      this.initialize();
    } else {
      this.ng2MapComponent.mapReady$.subscribe(map => this.initialize());
    }
  }

  initialize(): void {
    super.initialize();
    this.setPosition();
  }

  setPosition(): void {
    if (!this['position']) {
      this._subscriptions.push(this.ng2MapComp.geolocation.getCurrentPosition().subscribe(
        position => {
          console.log('setting marker position from current location');
          let latLng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
          this.mapObject.setPosition(latLng);
        },
        error => {
          console.error('ng2-map, error finding the current location');
          this.mapObject.setPosition(this.objectOptions['geoFallbackPosition'] || new google.maps.LatLng(0, 0));
        }
      ));
    } else if (typeof this['position'] === 'string') {
      this._subscriptions.push(this.ng2MapComp.geoCoder.geocode({address: this['position']}).subscribe(
        results => {
          console.log('setting marker position from address', this['position']);
          this.mapObject.setPosition(results[0].geometry.location);
        },
        error => {
          console.error('ng2-map, error finding the location from', this['position']);
          this.mapObject.setPosition(this.objectOptions['geoFallbackPosition'] || new google.maps.LatLng(0, 0));
        }
      ));
    }
  }
}
