import { Directive, Output, EventEmitter } from '@angular/core';

import { BaseMapDirective } from './base-map-directive';
import { Ng2MapComponent } from '../components/ng2-map.component';

const INPUTS = [
  'clickable', 'draggable', 'editable', 'fillColor', 'fillOpacity', 'geodesic', 'paths',
  'strokeColor', 'strokeOpacity', 'strokePosition', 'strokeWeight', 'visible', 'zIndex', 'options',
];
const OUTPUTS = [
  'click', 'dblclick', 'drag', 'dragend', 'dragstart', 'mousedown',
  'mousemove', 'mouseout', 'mouseover', 'mouseup', 'rightclick',
];

@Directive({
  selector: 'ng2-map>polygon, ng2-map>map-polygon',
  inputs: INPUTS,
  outputs: OUTPUTS,
})
export class Polygon extends BaseMapDirective {
  @Output() public click: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dblclick: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public drag: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dragend: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dragstart: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mousedown: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mousemove: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mouseout: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mouseover: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mouseup: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public rightclick: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js

  public clickable: any; // generated by ngc-pre-compiler.js
  public draggable: any; // generated by ngc-pre-compiler.js
  public editable: any; // generated by ngc-pre-compiler.js
  public fillColor: any; // generated by ngc-pre-compiler.js
  public fillOpacity: any; // generated by ngc-pre-compiler.js
  public geodesic: any; // generated by ngc-pre-compiler.js
  public paths: any; // generated by ngc-pre-compiler.js
  public strokeColor: any; // generated by ngc-pre-compiler.js
  public strokeOpacity: any; // generated by ngc-pre-compiler.js
  public strokePosition: any; // generated by ngc-pre-compiler.js
  public strokeWeight: any; // generated by ngc-pre-compiler.js
  public visible: any; // generated by ngc-pre-compiler.js
  public zIndex: any; // generated by ngc-pre-compiler.js
  public options: any; // generated by ngc-pre-compiler.js

  @Output() public initialized$: EventEmitter<any> = new EventEmitter();

  constructor(ng2MapComp: Ng2MapComponent) {
    super(ng2MapComp, 'Polygon', INPUTS, OUTPUTS);
  }
}
