import {Directive, Output, EventEmitter, Input} from '@angular/core';

import { BaseMapDirective } from './base-map-directive';
import { Ng2MapComponent } from '../components/ng2-map.component';

const INPUTS = [
  'clickable', 'draggable', 'editable', 'fillColor', 'fillOpacity', 'geodesic', 'paths',
  'strokeColor', 'strokeOpacity', 'strokePosition', 'strokeWeight', 'visible', 'zIndex', 'options',
];
const OUTPUTS = [
  'click', 'dblclick', 'drag', 'dragend', 'dragstart', 'mousedown',
  'mousemove', 'mouseout', 'mouseover', 'mouseup', 'rightclick',
];

@Directive({
  selector: 'ng2-map>polygon, ng2-map>map-polygon',
})
export class Polygon extends BaseMapDirective {
  @Output() public click: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dblclick: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public drag: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dragend: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dragstart: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mousedown: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mousemove: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mouseout: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mouseover: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mouseup: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public rightclick: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public initialized$: EventEmitter<any> = new EventEmitter();

  @Input() public clickable: any; // generated by ngc-pre-compiler.js
  @Input() public draggable: any; // generated by ngc-pre-compiler.js
  @Input() public editable: any; // generated by ngc-pre-compiler.js
  @Input() public fillColor: any; // generated by ngc-pre-compiler.js
  @Input() public fillOpacity: any; // generated by ngc-pre-compiler.js
  @Input() public geodesic: any; // generated by ngc-pre-compiler.js
  @Input() public paths: any; // generated by ngc-pre-compiler.js
  @Input() public strokeColor: any; // generated by ngc-pre-compiler.js
  @Input() public strokeOpacity: any; // generated by ngc-pre-compiler.js
  @Input() public strokePosition: any; // generated by ngc-pre-compiler.js
  @Input() public strokeWeight: any; // generated by ngc-pre-compiler.js
  @Input() public visible: any; // generated by ngc-pre-compiler.js
  @Input() public zIndex: any; // generated by ngc-pre-compiler.js
  @Input() public options: any; // generated by ngc-pre-compiler.js

  constructor(ng2MapComp: Ng2MapComponent) {
    super(ng2MapComp, 'Polygon', INPUTS, OUTPUTS);
  }
}
