import {Directive, Output, EventEmitter, Input} from '@angular/core';

import { BaseMapDirective } from './base-map-directive';
import { Ng2MapComponent } from '../components/ng2-map.component';

const INPUTS = [
  'clickable', 'draggable', 'editable', 'geodesic', 'icons', 'path', 'strokeColor',
  'strokeOpacity', 'strokeWeight', 'visible', 'zIndex', 'options'
];
const OUTPUTS = [
  'click', 'dblclick', 'drag', 'dragend', 'dragstart', 'mousedown',
  'mousemove', 'mouseout', 'mouseover', 'mouseup', 'rightclick'
];

@Directive({
  selector: 'ng2-map > polyline',
})
export class Polyline extends BaseMapDirective {
  @Output() public click: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dblclick: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public drag: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dragend: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dragstart: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mousedown: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mousemove: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mouseout: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mouseover: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mouseup: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public rightclick: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public initialized$: EventEmitter<any> = new EventEmitter();

  @Input() public clickable: any; // generated by ngc-pre-compiler.js
  @Input() public draggable: any; // generated by ngc-pre-compiler.js
  @Input() public editable: any; // generated by ngc-pre-compiler.js
  @Input() public geodesic: any; // generated by ngc-pre-compiler.js
  @Input() public icons: any; // generated by ngc-pre-compiler.js
  @Input() public path: any; // generated by ngc-pre-compiler.js
  @Input() public strokeColor: any; // generated by ngc-pre-compiler.js
  @Input() public strokeOpacity: any; // generated by ngc-pre-compiler.js
  @Input() public strokeWeight: any; // generated by ngc-pre-compiler.js
  @Input() public visible: any; // generated by ngc-pre-compiler.js
  @Input() public zIndex: any; // generated by ngc-pre-compiler.js
  @Input() public options: any; // generated by ngc-pre-compiler.js

  constructor(ng2MapComp: Ng2MapComponent) {
    super(ng2MapComp, 'Polyline', INPUTS, OUTPUTS);
  }
}

