import {Directive, Output, EventEmitter, Input} from '@angular/core';
import { BaseMapDirective } from './base-map-directive';
import { Ng2MapComponent } from '../components/ng2-map.component';

const INPUTS = ['autoRefresh', 'options' ];

@Directive({
  selector: 'ng2-map > traffic-layer',
})
export class TrafficLayer extends BaseMapDirective {
  @Input() public autoRefresh: any; // generated by ngc-pre-compiler.js
  @Input() public options: any; // generated by ngc-pre-compiler.js

  @Output() public initialized$: EventEmitter<any> = new EventEmitter();

  constructor(ng2MapComp: Ng2MapComponent) {
    super(ng2MapComp, 'TrafficLayer', INPUTS);
  }
}