import {
  Component,
  ElementRef,
  ViewEncapsulation,
  NgZone,
  EventEmitter,
  SimpleChanges,
  Inject,
  Output,
  Optional
} from '@angular/core';

import { OptionBuilder } from '../services/option-builder';
import { NavigatorGeolocation } from '../services/navigator-geolocation';
import { NG_MAP_CONFIG_TOKEN } from '../services/config';
import { GeoCoder } from '../services/geo-coder';
import { Ng2Map } from '../services/ng2-map';
import { Subject } from 'rxjs/Subject';
import { debounceTime } from 'rxjs/operator/debounceTime';
import { IJson, toCamelCase } from '../services/util';

const INPUTS = [
  'backgroundColor', 'center', 'disableDefaultUI', 'disableDoubleClickZoom', 'draggable', 'draggableCursor',
  'draggingCursor', 'heading', 'keyboardShortcuts', 'mapMaker', 'mapTypeControl', 'mapTypeId', 'maxZoom', 'minZoom',
  'noClear', 'overviewMapControl', 'panControl', 'panControlOptions', 'rotateControl', 'scaleControl', 'scrollwheel',
  'streetView', 'styles', 'tilt', 'zoom', 'streetViewControl', 'zoomControl', 'mapTypeControlOptions',
  'overviewMapControlOptions', 'rotateControlOptions', 'scaleControlOptions', 'streetViewControlOptions',
  'options',
  // ng2-map-specific inputs
  'geoFallbackCenter'
];

const OUTPUTS = [
  'bounds_changed', 'center_changed', 'click', 'dblclick', 'drag', 'dragend', 'dragstart', 'heading_changed', 'idle',
  'typeid_changed', 'mousemove', 'mouseout', 'mouseover', 'projection_changed', 'resize', 'rightclick',
  'tilesloaded', 'tile_changed', 'zoom_changed',
  // to avoid DOM event conflicts
  'mapClick', 'mapMouseover', 'mapMouseout', 'mapMousemove', 'mapDrag', 'mapDragend', 'mapDragstart'
];

@Component({
  selector: 'ng2-map',
  providers: [Ng2Map, OptionBuilder, GeoCoder, NavigatorGeolocation],
  styles: [`
    ng2-map {display: block; height: 300px;}
    .google-map {width: 100%; height: 100%}
  `],
  inputs: INPUTS,
  outputs: OUTPUTS,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div class="google-map"></div>
    <ng-content></ng-content>
  `,
})
<<<<<<< HEAD
export class Ng2MapComponent {
=======
export class Ng2MapComponent implements OnChanges, OnDestroy, AfterViewInit {
  @Output() public bounds_changed: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public center_changed: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public click: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dblclick: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public drag: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dragend: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public dragstart: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public heading_changed: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public idle: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public typeid_changed: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mousemove: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mouseout: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mouseover: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public projection_changed: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public resize: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public rightclick: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public tilesloaded: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public tile_changed: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public zoom_changed: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mapClick: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mapMouseover: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mapMouseout: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mapMousemove: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mapDrag: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mapDragend: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
  @Output() public mapDragstart: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js

  public backgroundColor: any; // generated by ngc-pre-compiler.js
  public center: any; // generated by ngc-pre-compiler.js
  public disableDefaultUI: any; // generated by ngc-pre-compiler.js
  public disableDoubleClickZoom: any; // generated by ngc-pre-compiler.js
  public draggable: any; // generated by ngc-pre-compiler.js
  public draggableCursor: any; // generated by ngc-pre-compiler.js
  public draggingCursor: any; // generated by ngc-pre-compiler.js
  public heading: any; // generated by ngc-pre-compiler.js
  public keyboardShortcuts: any; // generated by ngc-pre-compiler.js
  public mapMaker: any; // generated by ngc-pre-compiler.js
  public mapTypeControl: any; // generated by ngc-pre-compiler.js
  public mapTypeId: any; // generated by ngc-pre-compiler.js
  public maxZoom: any; // generated by ngc-pre-compiler.js
  public minZoom: any; // generated by ngc-pre-compiler.js
  public noClear: any; // generated by ngc-pre-compiler.js
  public overviewMapControl: any; // generated by ngc-pre-compiler.js
  public panControl: any; // generated by ngc-pre-compiler.js
  public panControlOptions: any; // generated by ngc-pre-compiler.js
  public rotateControl: any; // generated by ngc-pre-compiler.js
  public scaleControl: any; // generated by ngc-pre-compiler.js
  public scrollwheel: any; // generated by ngc-pre-compiler.js
  public streetView: any; // generated by ngc-pre-compiler.js
  public styles: any; // generated by ngc-pre-compiler.js
  public tilt: any; // generated by ngc-pre-compiler.js
  public zoom: any; // generated by ngc-pre-compiler.js
  public streetViewControl: any; // generated by ngc-pre-compiler.js
  public zoomControl: any; // generated by ngc-pre-compiler.js
  public mapTypeControlOptions: any; // generated by ngc-pre-compiler.js
  public overviewMapControlOptions: any; // generated by ngc-pre-compiler.js
  public rotateControlOptions: any; // generated by ngc-pre-compiler.js
  public scaleControlOptions: any; // generated by ngc-pre-compiler.js
  public streetViewControlOptions: any; // generated by ngc-pre-compiler.js
  public options: any; // generated by ngc-pre-compiler.js
  public geoFallbackCenter: any; // generated by ngc-pre-compiler.js

>>>>>>> 71cb355... output input replacement
  @Output() public mapReady$: EventEmitter<any> = new EventEmitter();

  public mapIndex: number;
  public el: HTMLElement;
  public map: google.maps.Map;
  public mapOptions: google.maps.MapOptions = {};

  public inputChanges$ = new Subject();

  // map objects by group
  public infoWindows: any = {};

  // map init path
  public mapInitPath: number; // 1: init after loading google api first, 2: init when view is initialized

  // map has been fully initialized
  public mapIdledOnce: boolean = false;

  constructor(
    public optionBuilder: OptionBuilder,
    public elementRef: ElementRef,
    public zone: NgZone,
    public geolocation: NavigatorGeolocation,
    public geoCoder: GeoCoder,
    public ng2Map: Ng2Map,
    @Optional() @Inject(NG_MAP_CONFIG_TOKEN) private config
  ) {
    this.config = this.config || {apiUrl: 'https://maps.google.com/maps/api/js'};

    (window as any)['ng2MapRef'] = (window as any)['ng2MapRef'] || [];
    this.mapIndex = (window as any)['ng2MapRef'].length;
    (window as any)['ng2MapRef'].push({ zone: this.zone, componentFn: () => this.initializeMap()});
    if (typeof google === 'undefined' || typeof google.maps === 'undefined' || !google.maps.Map) {
      this.mapInitPath = 1;
      this.addGoogleMapsApi();
    }
  }

  ngAfterViewInit(): void {
    if (this.mapInitPath !== 1) {
      this.initializeMap();
    }
  }

  ngOnChanges(changes: SimpleChanges) {
    this.inputChanges$.next(changes);
  }

  addGoogleMapsApi(): void {
    (window as any)['initNg2Map'] = (window as any)['initNg2Map'] || function() {
      (window as any)['ng2MapRef'].forEach( ng2MapRef => {
        ng2MapRef.zone.run(function() { ng2MapRef.componentFn(); });
      });
      (window as any)['ng2MapRef'].splice(0, (window as any)['ng2MapRef'].length);
    };
    if ((!(window as any)['google'] || !(window as any)['google']['maps']) && !document.querySelector('#ng2-map-api')) {
      let script = document.createElement( 'script' );
      script.id = 'ng2-map-api';

      // script.src = "https://maps.google.com/maps/api/js?callback=initNg2Map";
      let apiUrl = this.config.apiUrl ;
      apiUrl += apiUrl.indexOf('?') !== -1 ? '&' : '?';
      script.src = apiUrl + 'callback=initNg2Map';
      document.querySelector('body').appendChild(script);
    }
  }

  initializeMap(): void {
    this.el = this.elementRef.nativeElement.querySelector('.google-map');
    this.mapOptions = this.optionBuilder.googlizeAllInputs(INPUTS, this);
    console.log('ng2-map mapOptions', this.mapOptions);

    this.mapOptions.zoom = this.mapOptions.zoom || 15;
    typeof this.mapOptions.center === 'string' && (delete this.mapOptions.center);

    this.map = new google.maps.Map(this.el, this.mapOptions);
    this.map['mapObjectName'] = 'Ng2MapComponent';

    if (!this.mapOptions.center) { // if center is not given as lat/lng
      this.setCenter();
    }

    // set google events listeners and emits to this outputs listeners
    this.ng2Map.setObjectEvents(OUTPUTS, this, 'map');

    this.map.addListener('idle', () => {
      if (!this.mapIdledOnce) {
        this.mapIdledOnce = true;
        setTimeout(() => { // Why????, subsribe and emit must not be in the same cycle???
          this.mapReady$.emit(this.map);
        });
      }
    });

    // update map when input changes
    debounceTime.call(this.inputChanges$, 1000)
      .subscribe((changes: SimpleChanges) => this.ng2Map.updateGoogleObject(this.map, changes));

    // expose map object for test and debugging on (window as any)
    console.log('this.mapIndex', this.mapIndex);
    (window as any)['ng2MapRef'].map = this.map;
  }

  setCenter(): void {
    if (!this['center']) { // center is not from user. Thus, we set the current location
      this.geolocation.getCurrentPosition().subscribe(
        position => {
          console.log('setting map center from current location');
          let latLng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
          this.map.setCenter(latLng);
        },
        error => {
          console.error('ng2-map: Error finding the current position');
          this.map.setCenter(this.mapOptions['geoFallbackCenter'] || new google.maps.LatLng(0, 0));
        }
      );
    }
    else if (typeof this['center'] === 'string') {
      this.geoCoder.geocode({address: this['center']}).subscribe(
        results => {
          console.log('setting map center from address', this['center']);
          this.map.setCenter(results[0].geometry.location);
        },
        error => {
          this.map.setCenter(this.mapOptions['geoFallbackCenter'] || new google.maps.LatLng(0, 0));
        });
    }
  }

  openInfoWindow(id: string, anchor: google.maps.MVCObject, data: IJson) {
    this.infoWindows[id].open(anchor, data);
  }

  ngOnDestroy() {
    if (this.el) {
      OUTPUTS.forEach(output => google.maps.event.clearListeners(this.map, output));
    }
  }

  // map.markers, map.circles, map.heatmapLayers.. etc
  addToMapObjectGroup(mapObjectName: string, mapObject: any) {
    let groupName = toCamelCase(mapObjectName.toLowerCase()) + 's'; // e.g. markers
    this.map[groupName] = this.map[groupName] || [];
    this.map[groupName].push(mapObject);
  }

  removeFromMapObjectGroup(mapObjectName: string, mapObject: any) {
    let groupName = toCamelCase(mapObjectName.toLowerCase()) + 's'; // e.g. markers
    let index = this.map[groupName].indexOf(mapObject);
    console.log('index', mapObject, index);
    (index > -1) && this.map[groupName].splice(index, 1);
  }
}
